# Generated by Django 4.1.1 on 2022-10-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inked_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoo',
            name='image',
            field=models.CharField(max_length=3000),
        ),
    ]
